using System.Collections.Generic;
using System.IO;
using System.Text;

/// ponytail: Blueprints/*.json (db_Decks.json alone is 2.6MB) get deserialized via JsonFx into
/// Dictionary<string,object>[] - generic boxed containers that balloon far past the raw text
/// size and are never evicted, which is what pushed the 3DS (64MB total RAM) into OOM. This
/// reads a flat binary sibling file (generated by tools/json_to_bin.js) directly into the exact
/// same Dictionary<string,object>[] shape the game already expects, skipping JsonFx's
/// reflection-heavy parser and the JSON text entirely.
///
/// v2 format adds a deduplicated string table (measured: 99.4% of value occurrences in
/// db_Decks.json are repeats of one of only 806 unique strings) plus a per-file schema, so
/// repeated keys/values are stored once and referenced by index.
///
/// Format (little-endian, matches System.IO.BinaryReader on every platform regardless of host
/// endianness):
///   magic "BDB2" (4 bytes)
///   int32 stringTableCount, then per string: int32 byteLen + utf8 bytes
///   int16 schemaFieldCount, then per field: int32 stringTableIndex (the field's name)
///   int32 recordCount, then per record: int16 presentFieldCount,
///     then per present field: int16 schemaFieldIndex + int32 stringTableIndex (value)
public static class BlueprintBinaryReader_dbl
{
	private const string Magic = "BDB2";

	public static Dictionary<string, object>[] TryRead(string jsonRelativePath)
	{
		string binPath = ToBinPath(jsonRelativePath);
		string fullPath = ResolvePath(binPath);
		if (fullPath == null || !File.Exists(fullPath))
		{
			return null;
		}

		using (FileStream stream = File.OpenRead(fullPath))
		using (BinaryReader reader = new BinaryReader(stream, Encoding.UTF8))
		{
			byte[] magicBytes = reader.ReadBytes(4);
			if (Encoding.ASCII.GetString(magicBytes) != Magic)
			{
				return null;
			}

			int stringCount = reader.ReadInt32();
			string[] strings = new string[stringCount];
			for (int i = 0; i < stringCount; i++)
			{
				strings[i] = ReadLongString(reader);
			}

			short schemaFieldCount = reader.ReadInt16();
			string[] schemaFieldNames = new string[schemaFieldCount];
			for (int i = 0; i < schemaFieldCount; i++)
			{
				schemaFieldNames[i] = strings[reader.ReadInt32()];
			}

			int recordCount = reader.ReadInt32();
			Dictionary<string, object>[] records = new Dictionary<string, object>[recordCount];
			for (int i = 0; i < recordCount; i++)
			{
				short fieldCount = reader.ReadInt16();
				Dictionary<string, object> record = new Dictionary<string, object>(fieldCount);
				for (int f = 0; f < fieldCount; f++)
				{
					short schemaSlot = reader.ReadInt16();
					int valueIdx = reader.ReadInt32();
					record[schemaFieldNames[schemaSlot]] = strings[valueIdx];
				}
				records[i] = record;
			}
			return records;
		}
	}

	private static string ReadLongString(BinaryReader reader)
	{
		int len = reader.ReadInt32();
		byte[] bytes = reader.ReadBytes(len);
		return Encoding.UTF8.GetString(bytes);
	}

	private static string ToBinPath(string jsonRelativePath)
	{
		if (jsonRelativePath.EndsWith(".json"))
		{
			return jsonRelativePath.Substring(0, jsonRelativePath.Length - 5) + ".bin";
		}
		return jsonRelativePath + ".bin";
	}

	// ponytail: mirrors TFUtils.GetStreamingAssetsFile's own two-location lookup (persistent
	// data path override first, then StreamingAssets) so .bin sits wherever the .json would.
	private static string ResolvePath(string relativePath)
	{
		string persistentCandidate = Path.Combine(TFUtils.GetPersistentAssetsPath(), relativePath);
		if (File.Exists(persistentCandidate))
		{
			return persistentCandidate;
		}
		string streamingCandidate = Path.Combine(TFUtils.GetStreamingAssetsPath(), relativePath);
		if (streamingCandidate.Contains("://"))
		{
			return null;
		}
		return streamingCandidate;
	}
}
