Shader "N3DS/GUI/Text Shader" {
       Properties {
              _MainTex ("Font Texture", 2D) = "white" {}
              _Color ("Text Color", Color) = (1,1,1,1)
       }
       SubShader {
              Tags{ "QUEUE" = "Transparent" "IGNOREPROJECTOR" = "true" "RenderType" = "Transparent" }

              ZWrite Off
              Lighting Off
              Cull Off
              Fog { Mode Off }

              Blend SrcAlpha OneMinusSrcAlpha

              Pass {
                     // Bind the vertex colors generated by NGUI (UILabel)
                     BindChannels {
                            Bind "Color", color
                            Bind "Vertex", vertex
                            Bind "TexCoord", texcoord
                     }

                     // Combine the font texture alpha with vertex color and material color
                     SetTexture[_MainTex] {
                            constantColor[_Color]
                            // primary = Vertex Color passed by NGUI
                            // texture = Font texture map
                            // constant = Material tint color (_Color)
                            Combine primary * constant, texture alpha * primary alpha
                     }
              }
       }
       Fallback "GUI/Text Shader"
}